# AP 155 Lab Exercise
---
## Exercise 6: Matrices

_Instructions_: 
- **Report figure:** (See step 5 of the problem)
- **Report discussion:**
  - Explain the pattern shown in the report figure. 
- **Code**: Complete the code and ensure it is functional, error-free, readable, and efficient (where needed). Include concise Markdown documentation highlighting the critical steps of your algorithm for each problem.

### Student Information
- _Full Name (Last Name, First Name)_: 
- _Student No._: 20XX-XXXXX
- _Section_: THR-TX-X

### Grading Information (c/o Lab Instructor)
- [Rubrics description link](https://drive.google.com/file/d/1BMSlPot2Mc7XLu0eo4S8I8gLBsIadbCL/view?usp=sharing) (Note: percentages may still be tweaked)

| Criteria | Score | Subtotal |
| --- | --- | --- |
| Report figure | XX | 20 |
| Report discussion | XX | 20|
| Code readability | XX | 20 |
| Code efficiency | XX | 20 | 
| Code appropriateness  | XX | 20 | 
| **TOTAL** | XXX | 100 |

_Date and Time Scored (MM/DD/YYYY HH:MM AM/PM):_:_

---
## Section 1: Report

<!-- ### Report figure

<img src="figures/cat.jpg" alt="Alt text" width=45%> <img src="figures/cat.jpg" alt="Alt text" width=45%>


EDIT ME. See instruction above for what to include. Insert caption here, a short description what the figure illustrates. The syntax in markdown for putting a figure is `![Description](local_file_name.png)` or `<img src="/path/to_image.jpg" alt="Alt text" width=45%>`. Make sure the figure has complete elements.
-->

### Report discussion

EDIT ME. See instruction above for what to include. Insert your discussions here. Discuss your key results with at most 150 words per question.

### Other comments
- EDIT ME
- A self reflection can be placed here.
- This portion is not graded.
- You may insert further questions here.


---
## Section 2: Code

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math
from scipy.linalg import *

### Problem: Circuit Analysis

1. **Using Ohm's law and the Kirchhoff current law**, which says that the total net current flow out of (or into) any junction in a circuit must be zero, show that the voltages $V_1\ldots V_N$ satisfy the equations

$$3V_1 - V_2 - V_3 = V_+ $$
$$-V_1 + 4V_2 - V_3 - V_4 = V_+ $$
$$ \vdots$$
$$-V_{i-2} - V_{i-1} + 4V_i - V_{i+1} - V_{i+2} = 0 $$
$$\vdots$$
$$-V_{N-3} - V_{N-2} + 4V_{N-1} - V_N = 0$$
$$-V_{N-2} - V_{N-1} + 3V_N = 0$$

_Note: Do this by hand (no need for markdown output). You need $N \geq 5$ to see the complete pattern._ 

2. Express these equations in vector form $\mathbf{A}\mathbf{v} = \mathbf{w}$ and find the values of the matrix $\mathbf{A}$ and the vector $\mathbf{w}$. Write a program that generates the matrix $\mathbf{A}$ and vector $\mathbf{v}$ given the number of nodes $N$ and $V_+$.

3. Write a program to solve for the values of the $V_i$ when there are $N=6$ internal junctions with unknown voltages. (Hint: All the values of $V_i$ should lie between zero and $5$ [V].  If they don't, something is wrong.)

4. Now repeat your calculation for the case where there are $N=10\,000$ internal junctions.  This part is slow standard tools like the `solve` function from `np.linalg`. To solve efficiently, you need to make use of the fact that the matrix $\mathbf{A}$ is banded (and use Newman's `banded.py`).

5. Try different values of $N \in \{10, 50, 100, 500, 1000, 5000, 10000\}$. For each $N$, plot the junction voltage. Overlay all the curves on a single plot. What pattern do you see? Why?

#### Problem code summary

Include a brief summary (2–3 sentences) at the bottom of your code outlining the purpose of the script and its core algorithm. Focus on explaining why you wrote the code this way and the reasoning behind your implementation choices.

---
## Section 3 (Notes)

### Some codes for solving matrix problems

* solving matrix equations ($\bf{A}\vec{x} = \vec{b}$) -> `np.linalg.solve`
* LU-decomposition ($\bf{A} = \bf{L}\bf{U}$) -> `scipy.linalg.lu`
* matrix inversion ($\bf{A}^{-1}$) -> `np.linalg.inv`
* QR-decomposition ($\bf{A} = \bf{Q}\bf{R}$) -> `scipy.linalg.qr`
* eigenvalue problem ($\bf{A}\vec{x} = \lambda \vec{x}$) -> `np.linalg.eig`

Solving matrix problems by themselves isn't difficult. There is an abundance of linear algebra libraries that are ready to use: from the battle-tested ones (the classic [BLAS](https://www.netlib.org/blas/) and [LAPACK](https://www.netlib.org/lapack/)), HPC tools for large problems ([ScaLAPACK](https://netlib.org/scalapack/)), to hardware-accelerated ones often with GPUs ([cuBLAS](https://docs.nvidia.com/cuda/cublas/index.html) and [cuSolver](https://docs.nvidia.com/cuda/cusolver/index.html) for NVIDIA). 

The hardest part is actually composing the matrix. How do you transform a physical problem into a linear algebra problem?

* Circuit: https://personal.math.vt.edu/embree/cmda3606/chapter2.pdf
* Embree [main notes](https://personal.math.vt.edu/embree/cmda3606notes.pdf) + [lab manual](https://personal.math.vt.edu/embree/labman.pdf)

#### Sample Usage

In [2]:
A = np.array([[1,0,2],[-2,-1,3],[0,3,5]])
B = np.array([[-2],[1],[-3]])

# Known: A@B == C
A@B

array([[ -8],
       [ -6],
       [-12]])

In [3]:
sigma_z = np.array([[1,0],[0,-1]])
sigma_y = np.array([[0,-1j],[1j,0]])
sigma_x = np.array([[0,1],[1,0]])

In [4]:
ans1 = np.linalg.solve(sigma_x, sigma_y) # sigma_x @ ___ = sigma_y
ans2 = np.linalg.inv(A) @ B
print(ans1)
print(ans2)

[[0.+1.j 0.+0.j]
 [0.+0.j 0.-1.j]]
[[-1.07692308]
 [-0.23076923]
 [-0.46153846]]


In [5]:
from scipy.linalg import *
p, l, u = lu(A) 
# A = original matrix
# p = permutation matrix
# l = lower triangular of A
# u = upper triangular of A
A, p, l, u

(array([[ 1,  0,  2],
        [-2, -1,  3],
        [ 0,  3,  5]]),
 array([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]]),
 array([[ 1.        ,  0.        ,  0.        ],
        [-0.        ,  1.        ,  0.        ],
        [-0.5       , -0.16666667,  1.        ]]),
 array([[-2.        , -1.        ,  3.        ],
        [ 0.        ,  3.        ,  5.        ],
        [ 0.        ,  0.        ,  4.33333333]]))

### Sample Problem

Suppose you have a hanging mass M supported by two ropes (angled by $\alpha$ and $\beta$ with respect to the ceiling). Make a function that calculates the tension on each of the ropes. 


Newton's Laws Equation:
$$T_A\sin(\alpha) + T_B\sin(\beta) = Mg $$
$$T_A\cos(\alpha) - T_B\cos(\beta) = 0 $$


In [6]:
alpha = np.pi/6
beta = np.pi/3
M = 100/9.81
g = 9.81

A = np.array([
    [np.sin(alpha), np.sin(beta)],
    [np.cos(alpha), -np.cos(beta)]
])
w = np.array([[M*g], [0]])

np.linalg.solve(A,w)

array([[50.        ],
       [86.60254038]])

### np.roll

In [7]:
## Useful tips. Not required to solve the problems below!

# Suppose you have a Numpy array
x = np.zeros((4,4))
for row in x:
    print(row)

#rint(x[0,1:3])


# I can move all values to the left/right using roll
x_roll = np.roll(x, 1) # change 1 to -1, what happens? 
#x_roll2 = np.roll(x, -1)
print(x_roll)



[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Example of an Undetermined System

Masses $m_1, m_2, m_3$, and $m_4$ lie on a $2.00$ [m] beam of negligible mass. They are located $0.20, 0.70, 1.10$, and $1.40$ [m] away from the left end of the beam. Determine the masses $m_1, m_2, m_3$, and $m_4$, given the following constraints: 

- The total mass is $8.00$ [kg]
- If a pivot is placed halfway, the beam will balance if a $1.05$ [kg] mass is placed on the right-end of the beam
- If a pivot is placed $1.20$ [m] away from the right end, then the beam would balance if a $0.550$ [N m] torque were applied on the left end of the beam.
- If the system is split midway, the total mass on the left is $1.00$ [kg] heavier than the total mass on the right

In [8]:
#The matrix A and vector b (in Ax = b) would be:
b = [8, 1.05, -0.550, 1.00]
A = np.array([
    [1,1,1,1],
    [0.8,0.3,-0.1,-0.4],
    [0.6,0.1,-0.3,-0.6],
    [1,1,-1,-1]
])

In [9]:
np.linalg.matrix_rank(A), np.shape(A)[0]

(3, 4)

The rank is less than the number of rows
This is because in matrix A, the third row is a linear combination of the first two rows $(A_3 = A_2 - 0.2(A_1))$. Hence, this is an undetermined system (or could be an impossible system if the 2nd and 3rd condition cannot be satisfied at the same time).

What if we changed the problem: Suppose the 3rd condition (3rd bullet point) is changed to:

- *The mass of $m_1$ is $1.00 [kg]$*

In [10]:
Anew = A.copy()
bnew = b.copy()
Anew[2], bnew[2] = [1,0,0,0], 1

In [11]:
np.linalg.solve(Anew,bnew)

array([1. , 3.5, 2. , 1.5])